# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\"\x7f\n\x0bProductData\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x18\n\x10product_category\x18\x03 \x01(\t\x12\x16\n\x0eproduct_amount\x18\x04 \x01(\t\x12\x14\n\x0cproduct_unit\x18\x05 \x01(\t\"\xc2\x01\n\rWarehouseData\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\t\x12\x16\n\x0ewarehouse_name\x18\x02 \x01(\t\x12\x19\n\x11warehouse_country\x18\x03 \x01(\t\x12\x16\n\x0ewarehouse_city\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12,\n\x0cproduct_data\x18\x07 \x03(\x0b\x32\x16.warehouse.ProductData\"\x19\n\x17GetWarehouseDataRequest2f\n\x10WarehouseService\x12R\n\x10GetWarehouseData\x12\".warehouse.GetWarehouseDataRequest\x1a\x18.warehouse.WarehouseData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTDATA']._serialized_start=30
  _globals['_PRODUCTDATA']._serialized_end=157
  _globals['_WAREHOUSEDATA']._serialized_start=160
  _globals['_WAREHOUSEDATA']._serialized_end=354
  _globals['_GETWAREHOUSEDATAREQUEST']._serialized_start=356
  _globals['_GETWAREHOUSEDATAREQUEST']._serialized_end=381
  _globals['_WAREHOUSESERVICE']._serialized_start=383
  _globals['_WAREHOUSESERVICE']._serialized_end=485
# @@protoc_insertion_point(module_scope)
